{{/*
############################################################
# Copyright (c) 2024 Utilizable 
# Released under the MIT license
# ----------------------------------------------------------
#
# Deployment definition - stream
#
############################################################
*/}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{- include "stream.fullname" . }}"
  labels:
    {{- include "stream.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.global.annotations | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "stream.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "stream.labels" . | nindent 8 }}
    spec:
{{/*
  # --------------------------------------------
  # SETTINGS 
  # --------------------------------------------
*/}}
      {{- if .Values.stream.runtimeClassName }}
      runtimeClassName: {{ toYaml .Values.stream.runtimeClassName }}
      {{- end }}
      {{- with .Values.stream.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 2 }}
      {{- end }}
{{/*
  # --------------------------------------------
  # MAIN-CONTAINER 
  # --------------------------------------------
*/}}
      containers:
        - name: {{ .Chart.Name }} 
          {{- if .Values.stream.command }}
          command:
            {{- range .Values.stream.command }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          image: {{ 
                   include "metal.imageByParams" 
                   (dict "base" .Values.stream) 
                 }}
          imagePullPolicy: {{ .Values.stream.image.pullPolicy }}
          resources:
            {{- toYaml .Values.stream.resources | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "while [ $(curl -s -X GET http://127.0.0.1/metrics | grep \"^client_connected\" | awk '{print $2}') -gt 0 ]; do sleep 5; done"]
          env:
          {{- with .Values.stream.env }}
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
{{/*
  # --------------------------------------------
  # PORTS 
  # --------------------------------------------
*/}}
          {{- if .Values.stream.ports }}
          ports:
            {{- .Values.stream.ports | toYaml | nindent 12 }}
          {{- end }}
{{/*
  # --------------------------------------------
  # PROBES 
  # --------------------------------------------
*/}}

          {{- if .Values.stream.startupProbe.enabled }}
          startupProbe:
{{/* http probe */}}
            {{- if .Values.stream.startupProbe.httpGet }}
            httpGet:
              path: {{ .Values.stream.startupProbe.probePath }}
              scheme: {{ .Values.stream.startupProbe.scheme }}
              port: 8080 
            {{- end }}
{{/* cmd probe */}}
            {{- if .Values.stream.startupProbe.exec }}
            exec:
              command: 
              {{- range .Values.stream.startupProbe.exec.command }}
                - {{ . | quote }}
              {{- end }}
            {{- end }}

            initialDelaySeconds: {{ .Values.stream.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.stream.startupProbe.periodSeconds }}
            successThreshold: {{ .Values.stream.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.stream.startupProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.stream.startupProbe.timeoutSeconds }}
          {{- end }}

{{/*
  # --------------------------------------------
  # VOLUME MOUNTS 
  # --------------------------------------------
*/}}
          volumeMounts:
            {{- if .Values.stream.extraVolumesMounts }}
            {{- range .Values.stream.extraVolumesMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }} 
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- end }}
            {{- end }}
{{/*
  # --------------------------------------------
  # SIDECARS 
  # --------------------------------------------
*/}}
      {{- if .Values.stream.sidecars }}
        {{- .Values.stream.sidecars | toYaml | nindent 8 }}
      {{- end }}
{{/*
  # --------------------------------------------
  # VOLUMES 
  # --------------------------------------------
*/}}
      volumes:
        {{- if .Values.stream.extraVolumes }}
        {{- range .Values.stream.extraVolumes }}
{{/* 
  volumes - configMap
*/}}
        {{- if eq .type "configMap" }}
        - name: {{ .name }}
          configMap:
            name: {{ .name }}
        {{- end }}
{{/* 
  volumes - persistentVolumeClaim 
*/}}
        {{- if eq .type "persistentVolumeClaim" }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}
        {{- end }}
{{/* 
  volumes - emptyDIr 
*/}}
        {{- if eq .type "emptyDir" }}
        - name: {{ .name }}
          emptyDir: {}
        {{- end }}

        {{- end }}
        {{- end }}
...
