[program:sshd]
priority=70
command=/usr/bin/70_start_ssh.sh
# Logging
stdout_logfile=%(ENV_XDG_RUNTIME_DIR)s/logs/log_sshd
stdout_logfile_maxbytes=50MB
stderr_logfile=%(ENV_XDG_RUNTIME_DIR)s/logs/log_sshd
stderr_logfile_maxbytes=50MB
# Options
stopasgroup=true
stopsignal=TERM
environment=
  XDG_RUNTIME_DIR="%(ENV_XDG_RUNTIME_DIR)s"
# Start
autostart=true
autorestart=true
