{{/*
############################################################
# Copyright (c) 2024 wsadza 
# Released under the MIT license
# ----------------------------------------------------------
#
# Deployment definition - Gatekeeper 
#
############################################################
*/}}
---
{{- if .Values.gatekeeper.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{- include "gatekeeper.fullname" . }}"
  labels:
    {{- include "gatekeeper.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.global.annotations | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gatekeeper.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gatekeeper.labels" . | nindent 8 }}
    spec:
{{/*
  # --------------------------------------------
  # SETTINGS 
  # --------------------------------------------
*/}}
      {{- if .Values.gatekeeper.runtimeClassName }}
      runtimeClassName: {{ toYaml .Values.gatekeeper.runtimeClassName }}
      {{- end }}
      {{- with .Values.gatekeeper.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 2 }}
      {{- end }}
      {{- if .Values.gatekeeper.hostNetwork }}
      hostNetwork: {{ toYaml .Values.gatekeeper.hostNetwork }}
      {{- end }}
      {{- if .Values.gatekeeper.serviceAccountName }}
      serviceAccountName: {{ toYaml .Values.gatekeeper.serviceAccountName }}
      {{- end }}
{{/*
  # --------------------------------------------
  # MAIN-CONTAINER 
  # --------------------------------------------
*/}}
      containers:
        - name: {{ .Chart.Name }} 
          {{- if .Values.gatekeeper.command }}
          command:
            {{- range .Values.gatekeeper.command }}
              - {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.gatekeeper.args }}
          args:
            {{- range .Values.gatekeeper.args }}
              - {{ . | quote }}
            {{- end }}
          {{- end }}
          image: {{ 
                   include "metal.imageByParams" 
                   (dict "base" .Values.gatekeeper) 
                 }}
          imagePullPolicy: {{ .Values.gatekeeper.image.pullPolicy }}
          {{- if .Values.gatekeeper.resources }}
          resources:
            {{- toYaml .Values.gatekeeper.resources | nindent 12 }}
          env:
          {{- end }}
          {{- with .Values.gatekeeper.env }}
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
{{/*
  # --------------------------------------------
  # PORTS 
  # --------------------------------------------
*/}}
          {{- if .Values.gatekeeper.ports }}
          ports:
            {{- .Values.gatekeeper.ports | toYaml | nindent 12 }}
          {{- end }}
{{/*
  # --------------------------------------------
  # PROBES 
  # --------------------------------------------
*/}}
          {{- if .Values.gatekeeper.startupProbe.enabled }}
          startupProbe:
{{/* http probe */}}
            {{- if .Values.gatekeeper.startupProbe.httpGet }}
            httpGet:
              path: {{ .Values.gatekeeper.startupProbe.probePath }}
              scheme: {{ .Values.gatekeeper.startupProbe.scheme }}
              port: 8080 
            {{- end }}
{{/* cmd probe */}}
            {{- if .Values.gatekeeper.startupProbe.exec }}
            exec:
              command: 
              {{- range .Values.gatekeeper.startupProbe.exec.command }}
                - {{ . | quote }}
              {{- end }}
            {{- end }}

            initialDelaySeconds: {{ .Values.gatekeeper.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.gatekeeper.startupProbe.periodSeconds }}
            successThreshold: {{ .Values.gatekeeper.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.gatekeeper.startupProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.gatekeeper.startupProbe.timeoutSeconds }}
          {{- end }}
{{/*
  # --------------------------------------------
  # VOLUME MOUNTS 
  # --------------------------------------------
*/}}
          {{- if .Values.gatekeeper.extraVolumesMounts }}
          volumeMounts:
            {{- range .Values.gatekeeper.extraVolumesMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }} 
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- end }}
          {{- end }}
{{/*
  # --------------------------------------------
  # SIDECARS 
  # --------------------------------------------
*/}}
      {{- if .Values.gatekeeper.sidecars }}
        {{- .Values.gatekeeper.sidecars | toYaml | nindent 8 }}
      {{- end }}
{{/*
  # --------------------------------------------
  # VOLUMES 
  # --------------------------------------------
*/}}
      {{- if .Values.gatekeeper.extraVolumes }}
      volumes:
        {{- range .Values.gatekeeper.extraVolumes }}
{{/* 
  volumes - configMap
*/}}
        {{- if eq .type "configMap" }}
        - name: {{ .name }}
          configMap:
            name: {{ .name }}
        {{- end }}
{{/* 
  volumes - persistentVolumeClaim 
*/}}
        {{- if eq .type "persistentVolumeClaim" }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}
        {{- end }}
{{/* 
  volumes - emptyDIr 
*/}}
        {{- if eq .type "emptyDir" }}
        - name: {{ .name }}
          emptyDir: {}
        {{- end }}

        {{- end }}
      {{- end }}
...
{{- end }}
